@startuml
left to right direction
skinparam actorStyle awesome
skinparam usecase {
  BorderColor Black
  BackgroundColor White
}


actor Shopper as shopper
actor "Payment Processor" as payment
actor "Shipping Service" as shipping
actor "Admin" as admin


rectangle "Storefront System" as system {
  (Register and Log In to Account) as UC_Auth
  (Browse and Search Inventory) as UC_Inventory
  (Add and Manage Items in Cart) as UC_Cart
  (Checkout and Make Payment) as UC_Checkout
  (Review and Confirm Order) as UC_Confirm
  (Finalize and Complete Purchase) as UC_Complete
  (Manage Inventory and Generate Reports) as UC_Admin
}


shopper -- UC_Auth
shopper -- UC_Inventory
shopper -- UC_Cart
shopper -- UC_Checkout
shopper -- UC_Confirm
shopper -- UC_Complete

UC_Admin -- admin
UC_Cart -- admin
UC_Inventory -- admin
UC_Checkout -- admin
UC_Confirm -- admin
UC_Complete -- admin
  
UC_Checkout -- payment
shipping -- UC_Checkout
shipping -- UC_Confirm
@enduml